{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "php-app.fullname" . }}
  labels:
    {{- include "php-app.labels" . | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "php-app.selectorLabels" . | nindent 6 }}
  endpoints:
    # endpoints[].port is the Service port NAME, not the number.
    - port: nginx-metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
    - port: phpfpm-metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
